# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: ActionScript 3 CI

# Github worflows do not support actionscript directly.
# However the build uses ant, which is usually used to build java projects.
# The ant task (mxmlc) provided by the flex SDK (ant/lib/flexTasks.jar) is used to build the project.

on:
  push:
    # Just so the CI won't complain about Vanilla+ failing, since V+ isn't configured for CI.
    branches-ignore: [ master ]
  pull_request:
    branches: [ master-wip ]

env:
  # tell the build file where to find the flex SDK
  FLEX_HOME: "build-dep/bin/flex/"
  # this is to trick the flash player into thinking it is running on a desktop
  DISPLAY: ":1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download and install Android SDK
        uses: android-actions/setup-android@v3


      - name: Set up environment
        run: |
          echo "export PATH=\$PATH:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools" >> $GITHUB_ENV

      #add flex and air sdk
      - name: Download and install Adobe AIR SDK
        run: |
          AIR_VERSION="33.1.1.626"
          wget https://airsdk.harman.com/download/airsdk-linux-x64-v${AIR_VERSION}.tar.gz
          tar -xzvf airsdk-linux-x64-v${AIR_VERSION}.tar.gz
          echo "export AIR_HOME=$PWD" >> $GITHUB_ENV
          echo "export PATH=\$PATH:$AIR_HOME/bin" >> $GITHUB_ENV

      - name: Download and install Apache Flex SDK
        run: |
          FLEX_VERSION="4.16.1"
          wget https://archive.apache.org/dist/flex/${FLEX_VERSION}/apache-flex-sdk-${FLEX_VERSION}-bin.tar.gz
          tar -xzvf apache-flex-sdk-${FLEX_VERSION}-bin.tar.gz
          echo "export FLEX_HOME=$PWD/apache-flex-sdk-${FLEX_VERSION}" >> $GITHUB_ENV
          echo "export PATH=\$PATH:$FLEX_HOME/bin" >> $GITHUB_ENV

      # install VNC and xfce4 so we have a desktop, as the flash player requires one:
      - name: Install desktop
        run: sudo apt-get install tightvncserver xfce4 ant ant-optional -y

      # So flexunit can find the player and the ant build file does not have to be modified
      - name: Copy flashplayer to correct location
        run: sudo cp build-dep/bin/flashplayer /usr/local/bin/gflashplayer

      # start a VNC session, this will be the desktop for tests
      - name: Start VNC
        run: Xvnc :1 &

      # this is where the build happens. A separate build is started for every entry in the matrix element
      - name: Build
        run: ant allCI

      - name: save debug swf
        uses: actions/upload-artifact@v3
        with:
          name: debug-swf
          path: target/CoC-debug.swf

      - name: save release swf
        uses: actions/upload-artifact@v3
        with:
          name: release-swf
          path: target/CoC-release.swf

      - name: save android armv7 apk
        uses: actions/upload-artifact@v3
        with:
          name: mobile-apk
          path: target/CoC-Mobile-armv7.apk

      - name: save android armv8 apk
        uses: actions/upload-artifact@v3
        with:
          name: mobile-apk
          path: target/CoC-Mobile-arm8.apk