# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: ActionScript 3 CI

# Github worflows do not support actionscript directly.
# However the build uses ant, which is usually used to build java projects.
# The ant task (mxmlc) provided by the flex SDK (ant/lib/flexTasks.jar) is used to build the project.

on:
  push:
    # Just so the CI won't complain about Vanilla+ failing, since V+ isn't configured for CI.
    branches-ignore: [ master ]
  pull_request:
    branches: [ master-wip ]

env:
  # tell the build file where to find the flex SDK
  FLEX_HOME: "build-dep/bin/flex/"
  # this is to trick the flash player into thinking it is running on a desktop
  DISPLAY: ":1"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download and install Android SDK
        uses: android-actions/setup-android@v3

      - name: install flex sdk
        uses: joshtynjala/setup-apache-flex-action@v2
        with:
          flex-version: "4.16.1"
          air-version: "50.2.3.8"
          accept-air-license: true

      # install VNC and xfce4 so we have a desktop, as the flash player requires one:
      #- name: Install desktop
      #  run: sudo apt-get install tightvncserver xfce4 ant ant-optional -y

      # So flexunit can find the player and the ant build file does not have to be modified
      #- name: Copy flashplayer to correct location
      #  run: sudo cp build-dep/bin/flashplayer /usr/local/bin/gflashplayer

      # start a VNC session, this will be the desktop for tests
      - name: Start VNC
        run: Xvnc :1 &

      # this is where the build happens. A separate build is started for every entry in the matrix element
      - name: Build
        run: ant allCI

      - name: save debug swf
        uses: actions/upload-artifact@v3
        with:
          name: debug-swf
          path: target/CoC-debug.swf

      - name: save release swf
        uses: actions/upload-artifact@v3
        with:
          name: release-swf
          path: target/CoC-release.swf

      - name: save android armv7 apk
        uses: actions/upload-artifact@v3
        with:
          name: mobile-arm7-apk
          path: target/CoC-Mobile-armv7.apk

      - name: save android armv8 apk
        uses: actions/upload-artifact@v3
        with:
          name: mobile-arm8-apk
          path: target/CoC-Mobile-arm8.apk